[window]
startup_mode = 'Maximized'

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "w", mods = "Control", chars = "\u001BF" },
  { key = "b",  mods = "Control", chars = "\u001BB" }
]
